### ISSUE TITLE
SessionMiddleware can not works

### ISSUE THREAD

**Issue by dongweiming** [mitsuhiko/werkzeug#859] opened 2016-01-29 03:05 UTC
I have a short case:

```
# coding=utf-8
from flask import Flask
from werkzeug.contrib.sessions import (
    SessionMiddleware, FilesystemSessionStore)

app = Flask(__name__)
app.wsgi_app = SessionMiddleware(app.wsgi_app, FilesystemSessionStore())


@app.route('/')
def hello():
    return 'Hello'


if __name__ == '__main__':
    app.run(host='0.0.0.0', port=8081, debug=True)
```

but after i access http://localhost:8081, i found session do not set successfully, there have no cookie named `session_id`

because when sid is None, execute `new()` will return a session instance, but this session.should_save is False. so session will never be saved and can not set the cookie.  

related : https://github.com/mitsuhiko/werkzeug/pull/857

**Comment by remram44** [comment] 2016-02-01 19:11
#857 is an exact duplicate and was closed with "not a bug". Your session is empty and this is why no cookie gets set. `should_save` is False because `modified` is False.

cf [sessions.py:135](https://github.com/mitsuhiko/werkzeug/blob/d9e7736de41e7cbf5de70a15e28449b4dd4adab0/werkzeug/contrib/sessions.py#L135), this is the expected behavior.

**Comment by mitsuhiko** [comment] 2016-02-03 19:32
I'm going to close this as a duplicate.

**Closed by mitsuhiko** 2016-02-03 19:32 UTC
