### ISSUE TITLE
Exception in thread Thread-1 from latest update to werkzeug 0.11

### ISSUE THREAD

**Issue by samy100** [mitsuhiko/werkzeug#813] opened 2015-11-17 15:41 UTC
On [werkzeug release notes](http://werkzeug.pocoo.org/docs/0.11/changes/) it says `Devserver no longer requires SSL module to be installed`, but there's no mention any incompatibility problems that might arise because of that. I'm not even sure if that's causing the issue but it's the only thing that mentions ssl.

For some reason after updating from 0.10 to 0.11 I can't run my flask python code with werkzeug.

Startup Code:
```
context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
context.load_cert_chain('xxx.crt', 'xxx.key')
app.run(host='0.0.0.0', port=5000, ssl_context=context)
```
`# app is a flask application wrapper that basically wraps run_simple`

Exception Information:
```
INFO:app:Scheduler Started
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger pin code: xxx-xxx-xxx
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/.../python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/.../python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/.../venv/lib/python2.7/site-packages/werkzeug/serving.py", line 646, in inner
    fd=fd).serve_forever()
  File "/.../venv/lib/python2.7/site-packages/werkzeug/serving.py", line 550, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/.../venv/lib/python2.7/site-packages/werkzeug/serving.py", line 479, in __init__
    server_side=True)
  File "/.../python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 352, in wrap_socket
    _context=self)
  File "/.../python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 537, in __init__
    socket.__init__(self, _sock=sock._sock)
AttributeError: '_socket.socket' object has no attribute '_sock'
```

**Comment by mitsuhiko** [comment] 2015-11-17 15:45
The changelog entry is unrelated to this.  The problem you are encountering was a regression that was caused by changes in the internal socket handling code in the server.  This is fixed in 0.11.2.  The commit that fixes it is 83c61916c584ef42ad7e67894853fde5ba8b9ad0.

**Closed by mitsuhiko** 2015-11-17 15:45 UTC

**Comment by samy100** [comment] 2015-11-24 15:37
@mitsuhiko 

I'm still getting the same issue on 0.11.2

**Comment by mitsuhiko** [comment] 2015-11-24 22:35
Are you sure that is the same traceback? Can you please provide exact information of environment, python version and everything that can help to track this down.

**Comment by samy100** [comment] 2015-11-24 22:47
@mitsuhiko 
In terms of the environment, pretty much described above, but I'm using Python 2.7.10 with a virtualenv. I'm running a huge flask application and the startup script has basically the code above.

```
context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
context.load_cert_chain('xxx.crt', 'xxx.key')
app.run(host='0.0.0.0', port=5000, ssl_context=context, threaded=False)
```

I'm using MAC OS X Mavericks (10.9) and python is installed via *brew* using:
 `brew install python --universal --framework`

Here's the stack trace (I think it's exactly the same)

```
INFO:werkzeug: * Restarting with stat
INFO:apscheduler.scheduler:Scheduler started
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger pin code: xxx-xxx-xxx
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/.../python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/.../python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/.../venv/lib/python2.7/site-packages/werkzeug/serving.py", line 653, in inner
    fd=fd).serve_forever()
  File "/.../venv/lib/python2.7/site-packages/werkzeug/serving.py", line 557, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/.../venv/lib/python2.7/site-packages/werkzeug/serving.py", line 486, in __init__
    server_side=True)
  File "/.../python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 352, in wrap_socket
    _context=self)
  File "/.../python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 537, in __init__
    socket.__init__(self, _sock=sock._sock)
AttributeError: '_socket.socket' object has no attribute '_sock'
```

It works if I use `gunicorn` to startup the application instead of `.run`. Let me know if I can provide anything else that would be helpful. If I switch back to 0.10.4 it works.

**Comment by audrium** [comment] 2015-12-08 10:15
I've also noticed exactly the same error on 0.11. But for me it helped to install 0.11.2. Thanks!

**Comment by eliothxchan** [comment] 2015-12-08 16:23
I'm running into the same issue trying to run a Flask server from within a Docker container. The container's python version is 2.7.10.

My flask code:

```
    context = ssl.SSLContext(ssl.PROTOCOL_SSLv23)
    context.load_cert_chain(os.environ['PATH_SSL_CERT'], os.environ['PATH_SSL_KEY'])
    app.run(ssl_context=context, host='0.0.0.0', debug = True, port = 2025)
```

The stack trace:

```
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 247-483-355
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 653, in inner
    fd=fd).serve_forever()
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 557, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 486, in __init__
    server_side=True)
  File "/usr/local/lib/python2.7/ssl.py", line 352, in wrap_socket
    _context=self)
  File "/usr/local/lib/python2.7/ssl.py", line 537, in __init__
    socket.__init__(self, _sock=sock._sock)
AttributeError: '_socket.socket' object has no attribute '_sock'
```

**Comment by raidoz** [comment] 2015-12-08 17:39
I'm experiencing the same issue with werkzeug 0.11.2, flask 0.10.1 and python 2.7.9 on Debian jessie.
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 653, in inner
    fd=fd).serve_forever()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 557, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 486, in __init__
    server_side=True)
  File "/usr/lib/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 524, in __init__
    socket.__init__(self, _sock=sock._sock)
AttributeError: '_socket.socket' object has no attribute '_sock'
```

**Comment by thomashaukhush** [comment] 2015-12-11 23:20
Also experiencing the same issue with same traceback, with Python 2.7.11 on CentOS 6.7, with Flask 0.10.1 and Werkzeug 0.11.2, using a virtualenv.

**Comment by Link-** [comment] 2015-12-19 23:10
I'm also experiencing the same problem both on OS X 10.11.2 and Ubuntu 14.4.3 LTS. Here's the traceback and package info:

**Error + Traceback**
```
 * Restarting with stat
 * Debugger is active!
 * Debugger pin code: 257-405-669
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7.10/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7.10/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/srv/hubble/venv/lib/python2.7/site-packages/werkzeug/serving.py", line 653, in inner
    fd=fd).serve_forever()
  File "/srv/hubble/venv/lib/python2.7/site-packages/werkzeug/serving.py", line 557, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/srv/hubble/venv/lib/python2.7/site-packages/werkzeug/serving.py", line 486, in __init__
    server_side=True)
  File "/usr/local/lib/python2.7.10/lib/python2.7/ssl.py", line 352, in wrap_socket
    _context=self)
  File "/usr/local/lib/python2.7.10/lib/python2.7/ssl.py", line 537, in __init__
    socket.__init__(self, _sock=sock._sock)
AttributeError: '_socket.socket' object has no attribute '_sock'
```

**pip freeze output**
```
cffi==1.4.1
cryptography==1.1.2
enum34==1.1.1
Flask==0.10
Flask-Uploads==0.2.0
idna==2.0
ipaddress==1.0.15
itsdangerous==0.24
Jinja2==2.8
MarkupSafe==0.23
pyasn1==0.1.9
pycparser==2.14
pyOpenSSL==0.15.1
six==1.10.0
Werkzeug==0.11.2
wheel==0.24.0
```

**Setup code**
```
#!venv/bin/python
from app import app
from flask import send_from_directory
import ssl

# Setup SSL certificate
# TO BE REMOVED IN PRODUCTION
context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)
context.load_cert_chain(
	'/ssl-certs/cert.crt',
    '/ssl-certs/cert.key'
)

@app.route('/uploads/<path:path>')
def send_image(path):
	return send_from_directory('uploads', path)

# Debugging is enabled
# make sure this does
# not go into production
if __name__ == "__main__":
	app.run(
		host="0.0.0.0",
		port=int("5001"),
		debug=True,
		ssl_context=context
	)
```

**Comment by mitsuhiko** [comment] 2015-12-19 23:14
I just pushed out a release which should fix this.

**Comment by Link-** [comment] 2015-12-19 23:19
I can see it's merged with the master branch; safe to upgrade to 0.11.3 now?
