### ISSUE TITLE
url building with values supplied by MultiDict does not give multiple values

### ISSUE THREAD

**Issue by veelai** [mitsuhiko/werkzeug#658] opened 2015-01-27 08:45 UTC
When I try the following code
<pre>
from werkzeug.routing import Map, Rule
from werkzeug.datastructures import MultiDict
url_map = Map([Rule('/', endpoint='index'),])
urls = url_map.bind('localhost')
x = MultiDict()
x.setlist('a', [1, 3])
print(urls.build('index', x))
</pre>
I would expect to get '/?a=1&a=3' but it only returns '/?a=3'. I'm not entirely sure, that my expectation is warranted, but the code in werkzeug.routing.build looks like this should work as I expect it.

I used the master from yesterday on python 3.4.2.

**Comment by veelai** [comment] 2015-01-27 10:34
Applying the following pretty trivial patch solved this for me.

<pre>
From f6031c305330a72b9c0b7302d2ecd249de767340 Mon Sep 17 00:00:00 2001
From: Markus Oehme <veelai.1764@googlemail.com>
Date: Tue, 27 Jan 2015 11:29:56 +0100
Subject: [PATCH] routing.build: Use MultiDict for values.

Otherwise we loose values for keys which appear multiple times.
---
 werkzeug/routing.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/werkzeug/routing.py b/werkzeug/routing.py
index b9465d8..ba400bd 100644
--- a/werkzeug/routing.py
+++ b/werkzeug/routing.py
@@ -1641,7 +1641,7 @@ class MapAdapter(object):
                 valueiter = iteritems(values, multi=True)
             else:
                 valueiter = iteritems(values)
-            values = dict((k, v) for k, v in valueiter if v is not None)
+            values = MultiDict((k, v) for k, v in valueiter if v is not None)
         else:
             values = {}
 
-- 
2.2.2
</pre>

**Comment by untitaker** [comment] 2015-01-27 18:01
AFAIK it's not allowed to have query parameters with the same key, or at least it's unspecified behavior in the RFCs.

**Comment by veelai** [comment] 2015-01-27 18:10
Wikipedia says about query strings: "While there is no definitive standard, most web frameworks allow multiple values to be associated with a single field." and indeed this is not specified in RFC 3986. And it now works perfectly fine for me with werkzeug. :)

**Comment by veelai** [comment] 2015-01-29 10:04
What about this? I have a hobby project which currently kind of depends on this behaviour, so my question: will this probably make it into master or should I look for alternatives (whether that be patching locally or modifying my code)?

**Comment by untitaker** [comment] 2015-01-29 10:06
I wouldn't depend on this in any case. Even if it lands in master, the release cycle is very slow, so you will have to find an intermediate solution anyway, sorry.

**Comment by davidism** [comment] 2015-01-29 13:26
The following are all examples of multiple query parameters with the same name.

~~~python
>>> import requests
>>> r = requests.get('http://example.com/', params={'multi': [1, 2, 3]})
>>> r.url
'http://example.com/?multi=1&multi=2&multi=3'
~~~

This will also happen in any browser if you submit a multi-select field in a form with `method="GET"` but I didn't want to make a whole example for that.

Flask's `url_for` will handle multiple values for a key:

~~~python
>>> from flask import url_for
>>> url_for('example', test=[1, 2, 3])
'/example?test=1&test=2&test=3'
~~~

And so does it's underlying `url_map`:

~~~python
>>> urls = app.url_map.bind('localhost')
>>> urls.build('example', {'test': [1, 2, 3]})
'/example?test=1&test=2&test=3'
~~~

Werkzeug will decode such a query string into a `MultiDict`, so the reverse operation should also work.  The reverse operation basically works already as long as you convert the outgoing `MultiDict` to a `dict` first, as the last example shows.  There's no reason not to support `MultiDict` directly.

@untitaker I have no idea what the RFC says, but allowing multiple values is obviously standard behavior.

**Comment by untitaker** [comment] 2015-01-29 13:32
Found this: https://stackoverflow.com/questions/1746507/authoritative-position-of-duplicate-http-get-query-keys

So it appears to be common behavior but it's not standardized. Anyway, I'm convinced :S

@veelai Feel free to open a PR

**Comment by untitaker** [comment] 2015-01-29 14:11
Fixed by #660

**Closed by untitaker** 2015-01-29 14:11 UTC

**Comment by iurisilvio** [comment] 2015-02-02 22:21
I know it is already fixed, but I had the same issue after upgrade to 0.10. It was expected behaviour for me.

Thanks for the fix! Waiting for a release. For now, I just fixed my werkzeug to 0.9.6.

**Comment by galund** [comment] 2017-05-24 10:38
For anyone that was confused like me: this issue is still broken, because the fix was reverted due to <https://github.com/pallets/werkzeug/issues/709>.

Does anyone know if there is another ticket for this, or this one could be re-opened and a new fix considered?

Not being able to create URLs for forms that have multiple values seems a significant flaw (is causing me problems anyway).

**Comment by samuelhwilliams** [comment] 2017-08-24 13:08
Hey George. I'm having this problem too. How annoying!
