### ISSUE TITLE
environment can only contain strings

### ISSUE THREAD

**Issue by segalle** [mitsuhiko/werkzeug#467] opened 2013-12-03 09:01 UTC
when running runserver_plus i get an error message: "TypeError: environment can only contain strings" (running on windows 7 x64).

i checked the list of the os.environ items and found out that CELERY_LOADER is unicode and not string.

i fixed it by changing this line to:
os.environ.setdefault(str('CELERY_LOADER'), str('djcelery.loaders.DjangoLoader'))

**Comment by untitaker** [comment] 2015-02-07 01:40
Closing this because it really is not a bug for Werkzeug to work around at.

**Closed by untitaker** 2015-02-07 01:40 UTC
